### ISSUE TITLE
Display seems to always return null

### ISSUE THREAD

**Issue by dusta** [dframe/dframe#115]
To get rid of notification that display always return null

Replace 
``` php
     if (!empty($this->getBody())) {
            echo $this->getBody();
        }
```
To
```php
 return print $this->getBody();
```

**Comment by peter279k** [comment]
I don't  know why we have to use the `return print`.

I think the `return` is unused.

**Comment by peter279k** [comment]
And the `print` function in PHP will return the `int` type.

References: https://www.php.net/manual/en/function.print.php

**Comment by dusta** [comment]
It's for third-party applications like scrutinizer-ci.com and debuger phpstorm thats why there must be **return**

Yes. We do not use it but now they are not screaming 😃
