### ISSUE TITLE
compose.lock should be in repo

### ISSUE THREAD

**Issue by macwac** [dframe/dframe#125]
composer.lock should be in repo

**Comment by peter279k** [comment]
The `composer.lock` should be under the Git version control means we need to cache the dependencies.

And using this `composer.lock` to be consistency for the development environment.

It also makes dependencies installation fast, but we need to consider that we're possible to cache the abandoned/deprecated dependencies.

**Comment by dusta** [comment]
I am not convinced that he should be included in this project. In demo project yes https://github.com/dframe/dframe-demo  but in framework always should be latest

**Comment by peter279k** [comment]
I also agree with @dusta because we already have the `dframe-demo` repository.

And I think the `dframe-demo` should have the `composer.lock` and the `dframe` core framework should be latest because this can be convenient for us to use latest stable dependencies for our framework development :).
