### ISSUE TITLE
Import PSR-2 coding style tool

### ISSUE THREAD

**Issue by peter279k** [dframe/dframe#53]
As title, the PSR-2 coding style I think it's important for every repositories in this org.
And I think we can add the `PSR-2` coding style tool to detect the coding style and make these codes consistent. Consider the two coding style tools:

- [StyleCI](https://styleci.io/): It's a service that can check coding style automatically when pushing the latest commit.
-  [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer)

It can also add this required item in `CONTRIBUTING.md` :+1: .

**Comment by dusta** [comment]
Currently I'm using PHP_CodeSniffer in Visual Studio Code but this StyleCI is very interesting. In this weekend i will try integrate repo
