### ISSUE TITLE
Initialize CONTRIBUTING guide

### ISSUE THREAD

**Issue by peter279k** [dframe/dframe#54]
As title, it should add the `CONTRIBUTING` guide and let others can contribute this correctly.
Here is the `Requirements` section I suggest:

## Requirements

If the project maintainer has any additional requirements, you will find them listed here.

- **[PSR-2 Coding Standard](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md)** - The easiest way to apply the conventions is to install [PHP Code Sniffer](https://pear.php.net/package/PHP_CodeSniffer).

- **Add tests!** - Your patch won't be accepted if it doesn't have tests.

- **Document any change in behaviour** - Make sure the `README.md` and any other relevant documentation are kept up-to-date.

- **Consider our release cycle** - We try to follow [SemVer v2.0.0](https://semver.org/). Randomly breaking public APIs is not an option.

- **One pull request per feature** - If you want to do more than one thing, send multiple pull requests.

- **Send coherent history** - Make sure each individual commit in your pull request is meaningful. If you had to make multiple intermediate commits while developing, please [squash them](https://www.git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages) before submitting.

**Happy coding**!

Here is the requirements section [reference](https://github.com/spatie/code-outliner/blob/master/CONTRIBUTING.md#requirements).

**Comment by dusta** [comment]
I wonder why this file is empty I remember created it once with content many months ago.
