### ISSUE TITLE
Uncaught TypeError: Argument

### ISSUE THREAD

**Issue by dusta** [dframe/dframe#61]
When generating assesses throw

`[11-Aug-2018 10:31:56 UTC] PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Dframe\Asset\Exceptions\AsseticException::__construct() must be an instance of Exception or null, 
4. See error`

**Comment by peter279k** [comment]
It looks like inheritance the wrong class, and I think it should extend the `\Exception` class on this [line](https://github.com/dframe/dframe/blob/master/src/Asset/Exceptions/AsseticException.php#L17).

Please refer the `Example #2` in [official PHP doc](http://php.net/manual/en/language.exceptions.extending.php).

**Comment by dusta** [comment]
@peter279k Thank you for finding the problem.
