### ISSUE TITLE
getFingerprint method Dframe\Session class seems to be problematic

### ISSUE THREAD

**Issue by peter279k** [dframe/dframe#74]
**Describe the bug**
The `getFingerprint` has the undefined properties: 
`$this->ipAddress`, `$this->userAgent`, and `$this->name`.

**Expected behavior**
It should define these properties.

**Comment by peter279k** [comment]
@dusta, can you concern about this?

**Comment by dusta** [comment]
@peter279k Sorry for late message. You have right 👍 i will fix this in this weekend.
