### ISSUE TITLE
Demo isn't working

### ISSUE THREAD

**Issue by amadeuszxd** [dframe/dframe#8]
Hi,
I used this command
> $ composer create-project dframe/dframe-demo yourAppName 
and demo isn't work for me. 

The error:
`
Notice: Use of undefined constant APP_DIR - assumed 'APP_DIR' in D:\Programy\Xampp\7_1_9\htdocs\afterrent-api\vendor\dframe\dframe\src\Config.php on line 22

Fatal error: Uncaught Dframe\BaseException: Not Found Config APP_DIRConfig/router.php in D:\Programy\Xampp\7_1_9\htdocs\afterrent-api\vendor\dframe\dframe\src\Config.php:26 Stack trace: #0 D:\Programy\Xampp\7_1_9\htdocs\afterrent-api\vendor\dframe\dframe\src\Config.php(35): Dframe\Config->__construct('router', NULL) #1 D:\Programy\Xampp\7_1_9\htdocs\afterrent-api\vendor\dframe\dframe\src\Router.php(43): Dframe\Config::load('router') #2 D:\Programy\Xampp\7_1_9\htdocs\afterrent-api\vendor\dframe\dframe\src\Core.php(17): Dframe\Router->__construct() #3 D:\Programy\Xampp\7_1_9\htdocs\afterrent-api\web\index.php(13): Dframe\Core->run() #4 {main} thrown in D:\Programy\Xampp\7_1_9\htdocs\afterrent-api\vendor\dframe\dframe\src\Config.php on line 26`

**Comment by dusta** [comment]
dframe/dframe-demo was used the dev-master version. I fixed it.

Just in case 

`composer create-project dframe/dframe-demo yourAppName`

For test
`composer create-project dframe/dframe-demo yourAppName dev-master`
